// <auto-generated />
using FootballTeamInfo.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballTeamInfo.API.Migrations
{
    [DbContext(typeof(FootbalTeamInfoContext))]
    [Migration("20230318130755_FootballTeamInfoinitialMigration")]
    partial class FootballTeamInfoinitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("FootballTeamInfo.API.Entities.FootballTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FootballTeams");
                });

            modelBuilder.Entity("FootballTeamInfo.API.Entities.PlayerOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PlayerOfInterests");
                });

            modelBuilder.Entity("FootballTeamInfo.API.Entities.PlayerOfInterest", b =>
                {
                    b.HasOne("FootballTeamInfo.API.Entities.FootballTeam", "FootballTeam")
                        .WithMany("PlayersOfInterest")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FootballTeam");
                });

            modelBuilder.Entity("FootballTeamInfo.API.Entities.FootballTeam", b =>
                {
                    b.Navigation("PlayersOfInterest");
                });
#pragma warning restore 612, 618
        }
    }
}
